import Head from 'next/head';
import Message from '../components/message';
import {useEffect, useState} from "react";
import {db} from "../utils/firebase";
import { collection, query, orderBy, onSnapshot } from '../node_modules/@firebase/firestore';
import Link from "next/link";
import {motion} from "framer-motion";


export default function Home() {
  //Create a state with all the posts
const [allPosts, setAllPosts] = useState([]);

const getPosts = async () => {
  const collectionRef = collection(db, 'posts');
  const q = query(collectionRef, orderBy('timestamp', 'desc'));
  const unsubscribe = onSnapshot(q, (snapshot) => {
    setAllPosts(snapshot.docs.map((doc) => ({...doc.data(), id: doc.id})))
  });
  return unsubscribe
}

useEffect(() => {
  getPosts();
}, []);

  return (
    <motion.div
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 0.75, ease: "easeOut"}}
    >
      <Head>
        <title>My Blog project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div className="my-80 p-1">
  <h1 className="text-6xl text-center">
    Welcome to The Blog
  </h1>
</div>
      <div className="my-12 text-lg">
        <h2>See what other people are saying</h2>
        {allPosts.map((post) => (
          <Message {...post} key={post.id}>
<Link href={{pathname: `/${post.id}`, query: {...post}}}>
<button>{post.comments?.length > 0 ? post.comments?.length : 0} comments</button> 
</Link>
          </Message>
        ))}
      </div>

      
    </motion.div>
  )
}
